<?php

/*
 * This file is part of PapiAI,
 * A simple but powerful PHP library for building AI agents.
 *
 * (c) Marcello Duarte <marcello.duarte@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace PapiAI\Core;

/**
 * Immutable value object representing an LLM response.
 *
 * Contains the generated text, any tool calls requested by the model,
 * structured data (when an output schema was used), and token usage statistics.
 */
final class Response
{
    /**
     * @param string $text The text response from the LLM
     * @param array|null $data Parsed structured data (if output schema was used)
     * @param array<ToolCall> $toolCalls Tool calls made by the LLM
     * @param array<Message> $messages Full conversation history
     * @param array $usage Token usage statistics
     * @param string|null $stopReason Why the response ended
     */
    public function __construct(
        public readonly string $text,
        public readonly ?array $data = null,
        public readonly array $toolCalls = [],
        public readonly array $messages = [],
        public readonly array $usage = [],
        public readonly ?string $stopReason = null,
    ) {
    }

    /**
     * Check if the response has tool calls.
     *
     * @return bool True if the model requested one or more tool invocations
     */
    public function hasToolCalls(): bool
    {
        return !empty($this->toolCalls);
    }

    /**
     * Check if the response has structured data.
     *
     * @return bool True if the response was parsed into structured data via an output schema
     */
    public function hasData(): bool
    {
        return $this->data !== null;
    }

    /**
     * Get the number of input tokens consumed by this request.
     *
     * @return int Input token count, or 0 if usage data is unavailable
     */
    public function getInputTokens(): int
    {
        return $this->usage['input_tokens'] ?? 0;
    }

    /**
     * Get the number of output tokens generated by this response.
     *
     * @return int Output token count, or 0 if usage data is unavailable
     */
    public function getOutputTokens(): int
    {
        return $this->usage['output_tokens'] ?? 0;
    }

    /**
     * Get total token count (input + output).
     *
     * @return int Combined token count for cost estimation
     */
    public function getTotalTokens(): int
    {
        return $this->getInputTokens() + $this->getOutputTokens();
    }

    /**
     * Create from an Anthropic API response payload.
     *
     * @param array $response Raw Anthropic API response
     * @param array<Message> $messages Conversation history to attach
     *
     * @return self Parsed response with text, tool calls, and usage
     */
    public static function fromAnthropic(array $response, array $messages = []): self
    {
        $text = '';
        $toolCalls = [];

        foreach ($response['content'] ?? [] as $block) {
            if ($block['type'] === 'text') {
                $text .= $block['text'];
            } elseif ($block['type'] === 'tool_use') {
                $toolCalls[] = ToolCall::fromAnthropic($block);
            }
        }

        return new self(
            text: $text,
            toolCalls: $toolCalls,
            messages: $messages,
            usage: $response['usage'] ?? [],
            stopReason: $response['stop_reason'] ?? null,
        );
    }

    /**
     * Create from an OpenAI API response payload.
     *
     * @param array $response Raw OpenAI API response
     * @param array<Message> $messages Conversation history to attach
     *
     * @return self Parsed response with text, tool calls, and usage
     */
    public static function fromOpenAI(array $response, array $messages = []): self
    {
        $choice = $response['choices'][0] ?? [];
        $message = $choice['message'] ?? [];

        $toolCalls = [];
        foreach ($message['tool_calls'] ?? [] as $tc) {
            $toolCalls[] = ToolCall::fromOpenAI($tc);
        }

        return new self(
            text: $message['content'] ?? '',
            toolCalls: $toolCalls,
            messages: $messages,
            usage: $response['usage'] ?? [],
            stopReason: $choice['finish_reason'] ?? null,
        );
    }

    /**
     * Return a new Response with structured data attached.
     *
     * @param array $data The parsed structured data to include
     *
     * @return self A new immutable Response instance with the data set
     */
    public function withData(array $data): self
    {
        return new self(
            text: $this->text,
            data: $data,
            toolCalls: $this->toolCalls,
            messages: $this->messages,
            usage: $this->usage,
            stopReason: $this->stopReason,
        );
    }
}
